### ISSUE TITLE
search has priority for min block size over min chunk size

### ISSUE THREAD

**Issue by theglotzerify** [Nukelawe/slimefinder#11]
i have the min chunk size set to a specific value x and set the chunk weight to 255 to only get results hat have at least the amount x of chunks fully within the despawn sphere. however i still get results that have less chunks if they meet the min block amount which i have set to x*256. so it still counts blocks that are not making up full chunks towards the min block size. is there away to disable the blocksize check for the result and only enter something as a result if it meets the min chunk size?

**Comment by Nukelawe** [comment]
The block size and cluster size checks have an OR relationship between them. A chunk is considered a match if it satisfies either one of the criteria. To disable the block size criterion set the min-block-size property to something impossibly large, for example 73984=17x17x256, which is the block size of a 17x17 cluster full of slime chunks. Likewise, to disable the chunk check set the min-chunk-size to something larger than 289=17x17.

To avoid this kind of confusion for new users I might at some point change the default criteria to reject everything instead of accepting everything like it currently does.
